# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 01:18
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
